// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shuffleInfo.proto

#include "shuffleInfo.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace ShuffleInfo {
constexpr ReorderInfo_BinaryInfo::ReorderInfo_BinaryInfo(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : rand_obj_offset_(PROTOBUF_ULONGLONG(0)){}
struct ReorderInfo_BinaryInfoDefaultTypeInternal {
  constexpr ReorderInfo_BinaryInfoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ReorderInfo_BinaryInfoDefaultTypeInternal() {}
  union {
    ReorderInfo_BinaryInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ReorderInfo_BinaryInfoDefaultTypeInternal _ReorderInfo_BinaryInfo_default_instance_;
constexpr ReorderInfo_LayoutInfo::ReorderInfo_LayoutInfo(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : info_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , bb_size_(0u)
  , type_(0u)
  , bb_fallthrough_(false)
  , section_(0u)
  , src_type_(0u){}
struct ReorderInfo_LayoutInfoDefaultTypeInternal {
  constexpr ReorderInfo_LayoutInfoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ReorderInfo_LayoutInfoDefaultTypeInternal() {}
  union {
    ReorderInfo_LayoutInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ReorderInfo_LayoutInfoDefaultTypeInternal _ReorderInfo_LayoutInfo_default_instance_;
constexpr ReorderInfo_FixupInfo_FixupTuple::ReorderInfo_FixupInfo_FixupTuple(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : info_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , offset_(PROTOBUF_ULONGLONG(0))
  , base_bbl_sym_(PROTOBUF_ULONGLONG(0))
  , type_(0u)
  , base_section_(0u)
  , target_bbl_sym_(PROTOBUF_ULONGLONG(0))
  , target_section_(0u)
  , section_(0u)
  , add_(PROTOBUF_LONGLONG(0))
  , step_(0u){}
struct ReorderInfo_FixupInfo_FixupTupleDefaultTypeInternal {
  constexpr ReorderInfo_FixupInfo_FixupTupleDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ReorderInfo_FixupInfo_FixupTupleDefaultTypeInternal() {}
  union {
    ReorderInfo_FixupInfo_FixupTuple _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ReorderInfo_FixupInfo_FixupTupleDefaultTypeInternal _ReorderInfo_FixupInfo_FixupTuple_default_instance_;
constexpr ReorderInfo_FixupInfo::ReorderInfo_FixupInfo(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : text_()
  , rodata_()
  , data_()
  , datarel_()
  , initarray_()
  , got_()
  , init_()
  , fini_(){}
struct ReorderInfo_FixupInfoDefaultTypeInternal {
  constexpr ReorderInfo_FixupInfoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ReorderInfo_FixupInfoDefaultTypeInternal() {}
  union {
    ReorderInfo_FixupInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ReorderInfo_FixupInfoDefaultTypeInternal _ReorderInfo_FixupInfo_default_instance_;
constexpr ReorderInfo::ReorderInfo(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : layout_()
  , fixup_()
  , bin_(nullptr){}
struct ReorderInfoDefaultTypeInternal {
  constexpr ReorderInfoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ReorderInfoDefaultTypeInternal() {}
  union {
    ReorderInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ReorderInfoDefaultTypeInternal _ReorderInfo_default_instance_;
}  // namespace ShuffleInfo
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_shuffleInfo_2eproto[5];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_shuffleInfo_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_shuffleInfo_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_shuffleInfo_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_BinaryInfo, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_BinaryInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_BinaryInfo, rand_obj_offset_),
  0,
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_LayoutInfo, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_LayoutInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_LayoutInfo, bb_size_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_LayoutInfo, type_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_LayoutInfo, bb_fallthrough_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_LayoutInfo, section_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_LayoutInfo, src_type_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_LayoutInfo, info_),
  1,
  2,
  3,
  4,
  5,
  0,
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_FixupInfo_FixupTuple, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_FixupInfo_FixupTuple, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_FixupInfo_FixupTuple, offset_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_FixupInfo_FixupTuple, type_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_FixupInfo_FixupTuple, base_bbl_sym_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_FixupInfo_FixupTuple, base_section_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_FixupInfo_FixupTuple, target_bbl_sym_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_FixupInfo_FixupTuple, target_section_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_FixupInfo_FixupTuple, section_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_FixupInfo_FixupTuple, add_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_FixupInfo_FixupTuple, step_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_FixupInfo_FixupTuple, info_),
  1,
  3,
  2,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_FixupInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_FixupInfo, text_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_FixupInfo, rodata_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_FixupInfo, data_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_FixupInfo, datarel_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_FixupInfo, initarray_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_FixupInfo, got_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_FixupInfo, init_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo_FixupInfo, fini_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo, bin_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo, layout_),
  PROTOBUF_FIELD_OFFSET(::ShuffleInfo::ReorderInfo, fixup_),
  0,
  ~0u,
  ~0u,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 6, sizeof(::ShuffleInfo::ReorderInfo_BinaryInfo)},
  { 7, 18, sizeof(::ShuffleInfo::ReorderInfo_LayoutInfo)},
  { 24, 39, sizeof(::ShuffleInfo::ReorderInfo_FixupInfo_FixupTuple)},
  { 49, -1, sizeof(::ShuffleInfo::ReorderInfo_FixupInfo)},
  { 62, 70, sizeof(::ShuffleInfo::ReorderInfo)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::ShuffleInfo::_ReorderInfo_BinaryInfo_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::ShuffleInfo::_ReorderInfo_LayoutInfo_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::ShuffleInfo::_ReorderInfo_FixupInfo_FixupTuple_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::ShuffleInfo::_ReorderInfo_FixupInfo_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::ShuffleInfo::_ReorderInfo_default_instance_),
};

const char descriptor_table_protodef_shuffleInfo_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021shuffleInfo.proto\022\013ShuffleInfo\"\206\010\n\013Reo"
  "rderInfo\0220\n\003bin\030\001 \001(\0132#.ShuffleInfo.Reor"
  "derInfo.BinaryInfo\0223\n\006layout\030\002 \003(\0132#.Shu"
  "ffleInfo.ReorderInfo.LayoutInfo\0221\n\005fixup"
  "\030\003 \003(\0132\".ShuffleInfo.ReorderInfo.FixupIn"
  "fo\032%\n\nBinaryInfo\022\027\n\017rand_obj_offset\030\001 \001("
  "\004\032t\n\nLayoutInfo\022\017\n\007bb_size\030\001 \001(\r\022\014\n\004type"
  "\030\002 \001(\r\022\026\n\016bb_fallthrough\030\003 \001(\010\022\017\n\007sectio"
  "n\030\004 \001(\r\022\020\n\010src_type\030\005 \001(\r\022\014\n\004info\030\006 \001(\t\032"
  "\277\005\n\tFixupInfo\022;\n\004text\030\001 \003(\0132-.ShuffleInf"
  "o.ReorderInfo.FixupInfo.FixupTuple\022=\n\006ro"
  "data\030\002 \003(\0132-.ShuffleInfo.ReorderInfo.Fix"
  "upInfo.FixupTuple\022;\n\004data\030\003 \003(\0132-.Shuffl"
  "eInfo.ReorderInfo.FixupInfo.FixupTuple\022>"
  "\n\007datarel\030\004 \003(\0132-.ShuffleInfo.ReorderInf"
  "o.FixupInfo.FixupTuple\022@\n\tinitarray\030\005 \003("
  "\0132-.ShuffleInfo.ReorderInfo.FixupInfo.Fi"
  "xupTuple\022:\n\003got\030\006 \003(\0132-.ShuffleInfo.Reor"
  "derInfo.FixupInfo.FixupTuple\022;\n\004init\030\007 \003"
  "(\0132-.ShuffleInfo.ReorderInfo.FixupInfo.F"
  "ixupTuple\022;\n\004fini\030\010 \003(\0132-.ShuffleInfo.Re"
  "orderInfo.FixupInfo.FixupTuple\032\300\001\n\nFixup"
  "Tuple\022\016\n\006offset\030\001 \001(\004\022\014\n\004type\030\002 \001(\r\022\024\n\014b"
  "ase_bbl_sym\030\003 \001(\004\022\024\n\014base_section\030\004 \001(\r\022"
  "\026\n\016target_bbl_sym\030\005 \001(\004\022\026\n\016target_sectio"
  "n\030\006 \001(\r\022\017\n\007section\030\007 \001(\r\022\013\n\003add\030\010 \001(\003\022\014\n"
  "\004step\030\t \001(\r\022\014\n\004info\030\n \001(\t"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_shuffleInfo_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_shuffleInfo_2eproto = {
  false, false, 1065, descriptor_table_protodef_shuffleInfo_2eproto, "shuffleInfo.proto", 
  &descriptor_table_shuffleInfo_2eproto_once, nullptr, 0, 5,
  schemas, file_default_instances, TableStruct_shuffleInfo_2eproto::offsets,
  file_level_metadata_shuffleInfo_2eproto, file_level_enum_descriptors_shuffleInfo_2eproto, file_level_service_descriptors_shuffleInfo_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_shuffleInfo_2eproto_getter() {
  return &descriptor_table_shuffleInfo_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_shuffleInfo_2eproto(&descriptor_table_shuffleInfo_2eproto);
namespace ShuffleInfo {

// ===================================================================

class ReorderInfo_BinaryInfo::_Internal {
 public:
  using HasBits = decltype(std::declval<ReorderInfo_BinaryInfo>()._has_bits_);
  static void set_has_rand_obj_offset(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

ReorderInfo_BinaryInfo::ReorderInfo_BinaryInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:ShuffleInfo.ReorderInfo.BinaryInfo)
}
ReorderInfo_BinaryInfo::ReorderInfo_BinaryInfo(const ReorderInfo_BinaryInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  rand_obj_offset_ = from.rand_obj_offset_;
  // @@protoc_insertion_point(copy_constructor:ShuffleInfo.ReorderInfo.BinaryInfo)
}

void ReorderInfo_BinaryInfo::SharedCtor() {
rand_obj_offset_ = PROTOBUF_ULONGLONG(0);
}

ReorderInfo_BinaryInfo::~ReorderInfo_BinaryInfo() {
  // @@protoc_insertion_point(destructor:ShuffleInfo.ReorderInfo.BinaryInfo)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ReorderInfo_BinaryInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ReorderInfo_BinaryInfo::ArenaDtor(void* object) {
  ReorderInfo_BinaryInfo* _this = reinterpret_cast< ReorderInfo_BinaryInfo* >(object);
  (void)_this;
}
void ReorderInfo_BinaryInfo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ReorderInfo_BinaryInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ReorderInfo_BinaryInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:ShuffleInfo.ReorderInfo.BinaryInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  rand_obj_offset_ = PROTOBUF_ULONGLONG(0);
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReorderInfo_BinaryInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint64 rand_obj_offset = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_rand_obj_offset(&has_bits);
          rand_obj_offset_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ReorderInfo_BinaryInfo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ShuffleInfo.ReorderInfo.BinaryInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint64 rand_obj_offset = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->_internal_rand_obj_offset(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ShuffleInfo.ReorderInfo.BinaryInfo)
  return target;
}

size_t ReorderInfo_BinaryInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ShuffleInfo.ReorderInfo.BinaryInfo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional uint64 rand_obj_offset = 1;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_rand_obj_offset());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReorderInfo_BinaryInfo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ShuffleInfo.ReorderInfo.BinaryInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const ReorderInfo_BinaryInfo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ReorderInfo_BinaryInfo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ShuffleInfo.ReorderInfo.BinaryInfo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ShuffleInfo.ReorderInfo.BinaryInfo)
    MergeFrom(*source);
  }
}

void ReorderInfo_BinaryInfo::MergeFrom(const ReorderInfo_BinaryInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ShuffleInfo.ReorderInfo.BinaryInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_rand_obj_offset()) {
    _internal_set_rand_obj_offset(from._internal_rand_obj_offset());
  }
}

void ReorderInfo_BinaryInfo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ShuffleInfo.ReorderInfo.BinaryInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReorderInfo_BinaryInfo::CopyFrom(const ReorderInfo_BinaryInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ShuffleInfo.ReorderInfo.BinaryInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReorderInfo_BinaryInfo::IsInitialized() const {
  return true;
}

void ReorderInfo_BinaryInfo::InternalSwap(ReorderInfo_BinaryInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(rand_obj_offset_, other->rand_obj_offset_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ReorderInfo_BinaryInfo::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_shuffleInfo_2eproto_getter, &descriptor_table_shuffleInfo_2eproto_once,
      file_level_metadata_shuffleInfo_2eproto[0]);
}

// ===================================================================

class ReorderInfo_LayoutInfo::_Internal {
 public:
  using HasBits = decltype(std::declval<ReorderInfo_LayoutInfo>()._has_bits_);
  static void set_has_bb_size(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_type(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_bb_fallthrough(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_section(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_src_type(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_info(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

ReorderInfo_LayoutInfo::ReorderInfo_LayoutInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:ShuffleInfo.ReorderInfo.LayoutInfo)
}
ReorderInfo_LayoutInfo::ReorderInfo_LayoutInfo(const ReorderInfo_LayoutInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  info_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_info()) {
    info_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_info(), 
      GetArena());
  }
  ::memcpy(&bb_size_, &from.bb_size_,
    static_cast<size_t>(reinterpret_cast<char*>(&src_type_) -
    reinterpret_cast<char*>(&bb_size_)) + sizeof(src_type_));
  // @@protoc_insertion_point(copy_constructor:ShuffleInfo.ReorderInfo.LayoutInfo)
}

void ReorderInfo_LayoutInfo::SharedCtor() {
info_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&bb_size_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&src_type_) -
    reinterpret_cast<char*>(&bb_size_)) + sizeof(src_type_));
}

ReorderInfo_LayoutInfo::~ReorderInfo_LayoutInfo() {
  // @@protoc_insertion_point(destructor:ShuffleInfo.ReorderInfo.LayoutInfo)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ReorderInfo_LayoutInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  info_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ReorderInfo_LayoutInfo::ArenaDtor(void* object) {
  ReorderInfo_LayoutInfo* _this = reinterpret_cast< ReorderInfo_LayoutInfo* >(object);
  (void)_this;
}
void ReorderInfo_LayoutInfo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ReorderInfo_LayoutInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ReorderInfo_LayoutInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:ShuffleInfo.ReorderInfo.LayoutInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    info_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x0000003eu) {
    ::memset(&bb_size_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&src_type_) -
        reinterpret_cast<char*>(&bb_size_)) + sizeof(src_type_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReorderInfo_LayoutInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 bb_size = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_bb_size(&has_bits);
          bb_size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint32 type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_type(&has_bits);
          type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool bb_fallthrough = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          _Internal::set_has_bb_fallthrough(&has_bits);
          bb_fallthrough_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint32 section = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          _Internal::set_has_section(&has_bits);
          section_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint32 src_type = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          _Internal::set_has_src_type(&has_bits);
          src_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional string info = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          auto str = _internal_mutable_info();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ShuffleInfo.ReorderInfo.LayoutInfo.info");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ReorderInfo_LayoutInfo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ShuffleInfo.ReorderInfo.LayoutInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 bb_size = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_bb_size(), target);
  }

  // optional uint32 type = 2;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_type(), target);
  }

  // optional bool bb_fallthrough = 3;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_bb_fallthrough(), target);
  }

  // optional uint32 section = 4;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(4, this->_internal_section(), target);
  }

  // optional uint32 src_type = 5;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(5, this->_internal_src_type(), target);
  }

  // optional string info = 6;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_info().data(), static_cast<int>(this->_internal_info().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "ShuffleInfo.ReorderInfo.LayoutInfo.info");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_info(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ShuffleInfo.ReorderInfo.LayoutInfo)
  return target;
}

size_t ReorderInfo_LayoutInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ShuffleInfo.ReorderInfo.LayoutInfo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    // optional string info = 6;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_info());
    }

    // optional uint32 bb_size = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_bb_size());
    }

    // optional uint32 type = 2;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_type());
    }

    // optional bool bb_fallthrough = 3;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 1;
    }

    // optional uint32 section = 4;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_section());
    }

    // optional uint32 src_type = 5;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_src_type());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReorderInfo_LayoutInfo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ShuffleInfo.ReorderInfo.LayoutInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const ReorderInfo_LayoutInfo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ReorderInfo_LayoutInfo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ShuffleInfo.ReorderInfo.LayoutInfo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ShuffleInfo.ReorderInfo.LayoutInfo)
    MergeFrom(*source);
  }
}

void ReorderInfo_LayoutInfo::MergeFrom(const ReorderInfo_LayoutInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ShuffleInfo.ReorderInfo.LayoutInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_info(from._internal_info());
    }
    if (cached_has_bits & 0x00000002u) {
      bb_size_ = from.bb_size_;
    }
    if (cached_has_bits & 0x00000004u) {
      type_ = from.type_;
    }
    if (cached_has_bits & 0x00000008u) {
      bb_fallthrough_ = from.bb_fallthrough_;
    }
    if (cached_has_bits & 0x00000010u) {
      section_ = from.section_;
    }
    if (cached_has_bits & 0x00000020u) {
      src_type_ = from.src_type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ReorderInfo_LayoutInfo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ShuffleInfo.ReorderInfo.LayoutInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReorderInfo_LayoutInfo::CopyFrom(const ReorderInfo_LayoutInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ShuffleInfo.ReorderInfo.LayoutInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReorderInfo_LayoutInfo::IsInitialized() const {
  return true;
}

void ReorderInfo_LayoutInfo::InternalSwap(ReorderInfo_LayoutInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  info_.Swap(&other->info_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReorderInfo_LayoutInfo, src_type_)
      + sizeof(ReorderInfo_LayoutInfo::src_type_)
      - PROTOBUF_FIELD_OFFSET(ReorderInfo_LayoutInfo, bb_size_)>(
          reinterpret_cast<char*>(&bb_size_),
          reinterpret_cast<char*>(&other->bb_size_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ReorderInfo_LayoutInfo::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_shuffleInfo_2eproto_getter, &descriptor_table_shuffleInfo_2eproto_once,
      file_level_metadata_shuffleInfo_2eproto[1]);
}

// ===================================================================

class ReorderInfo_FixupInfo_FixupTuple::_Internal {
 public:
  using HasBits = decltype(std::declval<ReorderInfo_FixupInfo_FixupTuple>()._has_bits_);
  static void set_has_offset(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_type(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_base_bbl_sym(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_base_section(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_target_bbl_sym(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_target_section(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_section(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_add(HasBits* has_bits) {
    (*has_bits)[0] |= 256u;
  }
  static void set_has_step(HasBits* has_bits) {
    (*has_bits)[0] |= 512u;
  }
  static void set_has_info(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

ReorderInfo_FixupInfo_FixupTuple::ReorderInfo_FixupInfo_FixupTuple(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple)
}
ReorderInfo_FixupInfo_FixupTuple::ReorderInfo_FixupInfo_FixupTuple(const ReorderInfo_FixupInfo_FixupTuple& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  info_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_info()) {
    info_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_info(), 
      GetArena());
  }
  ::memcpy(&offset_, &from.offset_,
    static_cast<size_t>(reinterpret_cast<char*>(&step_) -
    reinterpret_cast<char*>(&offset_)) + sizeof(step_));
  // @@protoc_insertion_point(copy_constructor:ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple)
}

void ReorderInfo_FixupInfo_FixupTuple::SharedCtor() {
info_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&offset_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&step_) -
    reinterpret_cast<char*>(&offset_)) + sizeof(step_));
}

ReorderInfo_FixupInfo_FixupTuple::~ReorderInfo_FixupInfo_FixupTuple() {
  // @@protoc_insertion_point(destructor:ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ReorderInfo_FixupInfo_FixupTuple::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  info_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ReorderInfo_FixupInfo_FixupTuple::ArenaDtor(void* object) {
  ReorderInfo_FixupInfo_FixupTuple* _this = reinterpret_cast< ReorderInfo_FixupInfo_FixupTuple* >(object);
  (void)_this;
}
void ReorderInfo_FixupInfo_FixupTuple::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ReorderInfo_FixupInfo_FixupTuple::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ReorderInfo_FixupInfo_FixupTuple::Clear() {
// @@protoc_insertion_point(message_clear_start:ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    info_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x000000feu) {
    ::memset(&offset_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&section_) -
        reinterpret_cast<char*>(&offset_)) + sizeof(section_));
  }
  if (cached_has_bits & 0x00000300u) {
    ::memset(&add_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&step_) -
        reinterpret_cast<char*>(&add_)) + sizeof(step_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReorderInfo_FixupInfo_FixupTuple::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint64 offset = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_offset(&has_bits);
          offset_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint32 type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_type(&has_bits);
          type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint64 base_bbl_sym = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          _Internal::set_has_base_bbl_sym(&has_bits);
          base_bbl_sym_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint32 base_section = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          _Internal::set_has_base_section(&has_bits);
          base_section_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint64 target_bbl_sym = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          _Internal::set_has_target_bbl_sym(&has_bits);
          target_bbl_sym_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint32 target_section = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          _Internal::set_has_target_section(&has_bits);
          target_section_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint32 section = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56)) {
          _Internal::set_has_section(&has_bits);
          section_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional int64 add = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 64)) {
          _Internal::set_has_add(&has_bits);
          add_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint32 step = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 72)) {
          _Internal::set_has_step(&has_bits);
          step_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional string info = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 82)) {
          auto str = _internal_mutable_info();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple.info");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ReorderInfo_FixupInfo_FixupTuple::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint64 offset = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->_internal_offset(), target);
  }

  // optional uint32 type = 2;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_type(), target);
  }

  // optional uint64 base_bbl_sym = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(3, this->_internal_base_bbl_sym(), target);
  }

  // optional uint32 base_section = 4;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(4, this->_internal_base_section(), target);
  }

  // optional uint64 target_bbl_sym = 5;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(5, this->_internal_target_bbl_sym(), target);
  }

  // optional uint32 target_section = 6;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(6, this->_internal_target_section(), target);
  }

  // optional uint32 section = 7;
  if (cached_has_bits & 0x00000080u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(7, this->_internal_section(), target);
  }

  // optional int64 add = 8;
  if (cached_has_bits & 0x00000100u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(8, this->_internal_add(), target);
  }

  // optional uint32 step = 9;
  if (cached_has_bits & 0x00000200u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(9, this->_internal_step(), target);
  }

  // optional string info = 10;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_info().data(), static_cast<int>(this->_internal_info().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple.info");
    target = stream->WriteStringMaybeAliased(
        10, this->_internal_info(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple)
  return target;
}

size_t ReorderInfo_FixupInfo_FixupTuple::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional string info = 10;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_info());
    }

    // optional uint64 offset = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
          this->_internal_offset());
    }

    // optional uint64 base_bbl_sym = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
          this->_internal_base_bbl_sym());
    }

    // optional uint32 type = 2;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_type());
    }

    // optional uint32 base_section = 4;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_base_section());
    }

    // optional uint64 target_bbl_sym = 5;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
          this->_internal_target_bbl_sym());
    }

    // optional uint32 target_section = 6;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_target_section());
    }

    // optional uint32 section = 7;
    if (cached_has_bits & 0x00000080u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_section());
    }

  }
  if (cached_has_bits & 0x00000300u) {
    // optional int64 add = 8;
    if (cached_has_bits & 0x00000100u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
          this->_internal_add());
    }

    // optional uint32 step = 9;
    if (cached_has_bits & 0x00000200u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_step());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReorderInfo_FixupInfo_FixupTuple::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple)
  GOOGLE_DCHECK_NE(&from, this);
  const ReorderInfo_FixupInfo_FixupTuple* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ReorderInfo_FixupInfo_FixupTuple>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple)
    MergeFrom(*source);
  }
}

void ReorderInfo_FixupInfo_FixupTuple::MergeFrom(const ReorderInfo_FixupInfo_FixupTuple& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_info(from._internal_info());
    }
    if (cached_has_bits & 0x00000002u) {
      offset_ = from.offset_;
    }
    if (cached_has_bits & 0x00000004u) {
      base_bbl_sym_ = from.base_bbl_sym_;
    }
    if (cached_has_bits & 0x00000008u) {
      type_ = from.type_;
    }
    if (cached_has_bits & 0x00000010u) {
      base_section_ = from.base_section_;
    }
    if (cached_has_bits & 0x00000020u) {
      target_bbl_sym_ = from.target_bbl_sym_;
    }
    if (cached_has_bits & 0x00000040u) {
      target_section_ = from.target_section_;
    }
    if (cached_has_bits & 0x00000080u) {
      section_ = from.section_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x00000300u) {
    if (cached_has_bits & 0x00000100u) {
      add_ = from.add_;
    }
    if (cached_has_bits & 0x00000200u) {
      step_ = from.step_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ReorderInfo_FixupInfo_FixupTuple::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReorderInfo_FixupInfo_FixupTuple::CopyFrom(const ReorderInfo_FixupInfo_FixupTuple& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReorderInfo_FixupInfo_FixupTuple::IsInitialized() const {
  return true;
}

void ReorderInfo_FixupInfo_FixupTuple::InternalSwap(ReorderInfo_FixupInfo_FixupTuple* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  info_.Swap(&other->info_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReorderInfo_FixupInfo_FixupTuple, step_)
      + sizeof(ReorderInfo_FixupInfo_FixupTuple::step_)
      - PROTOBUF_FIELD_OFFSET(ReorderInfo_FixupInfo_FixupTuple, offset_)>(
          reinterpret_cast<char*>(&offset_),
          reinterpret_cast<char*>(&other->offset_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ReorderInfo_FixupInfo_FixupTuple::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_shuffleInfo_2eproto_getter, &descriptor_table_shuffleInfo_2eproto_once,
      file_level_metadata_shuffleInfo_2eproto[2]);
}

// ===================================================================

class ReorderInfo_FixupInfo::_Internal {
 public:
};

ReorderInfo_FixupInfo::ReorderInfo_FixupInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  text_(arena),
  rodata_(arena),
  data_(arena),
  datarel_(arena),
  initarray_(arena),
  got_(arena),
  init_(arena),
  fini_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:ShuffleInfo.ReorderInfo.FixupInfo)
}
ReorderInfo_FixupInfo::ReorderInfo_FixupInfo(const ReorderInfo_FixupInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      text_(from.text_),
      rodata_(from.rodata_),
      data_(from.data_),
      datarel_(from.datarel_),
      initarray_(from.initarray_),
      got_(from.got_),
      init_(from.init_),
      fini_(from.fini_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ShuffleInfo.ReorderInfo.FixupInfo)
}

void ReorderInfo_FixupInfo::SharedCtor() {
}

ReorderInfo_FixupInfo::~ReorderInfo_FixupInfo() {
  // @@protoc_insertion_point(destructor:ShuffleInfo.ReorderInfo.FixupInfo)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ReorderInfo_FixupInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ReorderInfo_FixupInfo::ArenaDtor(void* object) {
  ReorderInfo_FixupInfo* _this = reinterpret_cast< ReorderInfo_FixupInfo* >(object);
  (void)_this;
}
void ReorderInfo_FixupInfo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ReorderInfo_FixupInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ReorderInfo_FixupInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:ShuffleInfo.ReorderInfo.FixupInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  text_.Clear();
  rodata_.Clear();
  data_.Clear();
  datarel_.Clear();
  initarray_.Clear();
  got_.Clear();
  init_.Clear();
  fini_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReorderInfo_FixupInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple text = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_text(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple rodata = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_rodata(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple data = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_data(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple datarel = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_datarel(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple initarray = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_initarray(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple got = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_got(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple init = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_init(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<58>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple fini = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_fini(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<66>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ReorderInfo_FixupInfo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ShuffleInfo.ReorderInfo.FixupInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple text = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_text_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_text(i), target, stream);
  }

  // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple rodata = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_rodata_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_rodata(i), target, stream);
  }

  // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple data = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_data_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, this->_internal_data(i), target, stream);
  }

  // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple datarel = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_datarel_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, this->_internal_datarel(i), target, stream);
  }

  // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple initarray = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_initarray_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, this->_internal_initarray(i), target, stream);
  }

  // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple got = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_got_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, this->_internal_got(i), target, stream);
  }

  // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple init = 7;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_init_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, this->_internal_init(i), target, stream);
  }

  // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple fini = 8;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_fini_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(8, this->_internal_fini(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ShuffleInfo.ReorderInfo.FixupInfo)
  return target;
}

size_t ReorderInfo_FixupInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ShuffleInfo.ReorderInfo.FixupInfo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple text = 1;
  total_size += 1UL * this->_internal_text_size();
  for (const auto& msg : this->text_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple rodata = 2;
  total_size += 1UL * this->_internal_rodata_size();
  for (const auto& msg : this->rodata_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple data = 3;
  total_size += 1UL * this->_internal_data_size();
  for (const auto& msg : this->data_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple datarel = 4;
  total_size += 1UL * this->_internal_datarel_size();
  for (const auto& msg : this->datarel_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple initarray = 5;
  total_size += 1UL * this->_internal_initarray_size();
  for (const auto& msg : this->initarray_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple got = 6;
  total_size += 1UL * this->_internal_got_size();
  for (const auto& msg : this->got_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple init = 7;
  total_size += 1UL * this->_internal_init_size();
  for (const auto& msg : this->init_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple fini = 8;
  total_size += 1UL * this->_internal_fini_size();
  for (const auto& msg : this->fini_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReorderInfo_FixupInfo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ShuffleInfo.ReorderInfo.FixupInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const ReorderInfo_FixupInfo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ReorderInfo_FixupInfo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ShuffleInfo.ReorderInfo.FixupInfo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ShuffleInfo.ReorderInfo.FixupInfo)
    MergeFrom(*source);
  }
}

void ReorderInfo_FixupInfo::MergeFrom(const ReorderInfo_FixupInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ShuffleInfo.ReorderInfo.FixupInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  text_.MergeFrom(from.text_);
  rodata_.MergeFrom(from.rodata_);
  data_.MergeFrom(from.data_);
  datarel_.MergeFrom(from.datarel_);
  initarray_.MergeFrom(from.initarray_);
  got_.MergeFrom(from.got_);
  init_.MergeFrom(from.init_);
  fini_.MergeFrom(from.fini_);
}

void ReorderInfo_FixupInfo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ShuffleInfo.ReorderInfo.FixupInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReorderInfo_FixupInfo::CopyFrom(const ReorderInfo_FixupInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ShuffleInfo.ReorderInfo.FixupInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReorderInfo_FixupInfo::IsInitialized() const {
  return true;
}

void ReorderInfo_FixupInfo::InternalSwap(ReorderInfo_FixupInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  text_.InternalSwap(&other->text_);
  rodata_.InternalSwap(&other->rodata_);
  data_.InternalSwap(&other->data_);
  datarel_.InternalSwap(&other->datarel_);
  initarray_.InternalSwap(&other->initarray_);
  got_.InternalSwap(&other->got_);
  init_.InternalSwap(&other->init_);
  fini_.InternalSwap(&other->fini_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ReorderInfo_FixupInfo::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_shuffleInfo_2eproto_getter, &descriptor_table_shuffleInfo_2eproto_once,
      file_level_metadata_shuffleInfo_2eproto[3]);
}

// ===================================================================

class ReorderInfo::_Internal {
 public:
  using HasBits = decltype(std::declval<ReorderInfo>()._has_bits_);
  static const ::ShuffleInfo::ReorderInfo_BinaryInfo& bin(const ReorderInfo* msg);
  static void set_has_bin(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::ShuffleInfo::ReorderInfo_BinaryInfo&
ReorderInfo::_Internal::bin(const ReorderInfo* msg) {
  return *msg->bin_;
}
ReorderInfo::ReorderInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  layout_(arena),
  fixup_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:ShuffleInfo.ReorderInfo)
}
ReorderInfo::ReorderInfo(const ReorderInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      layout_(from.layout_),
      fixup_(from.fixup_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_bin()) {
    bin_ = new ::ShuffleInfo::ReorderInfo_BinaryInfo(*from.bin_);
  } else {
    bin_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:ShuffleInfo.ReorderInfo)
}

void ReorderInfo::SharedCtor() {
bin_ = nullptr;
}

ReorderInfo::~ReorderInfo() {
  // @@protoc_insertion_point(destructor:ShuffleInfo.ReorderInfo)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ReorderInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete bin_;
}

void ReorderInfo::ArenaDtor(void* object) {
  ReorderInfo* _this = reinterpret_cast< ReorderInfo* >(object);
  (void)_this;
}
void ReorderInfo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ReorderInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ReorderInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:ShuffleInfo.ReorderInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  layout_.Clear();
  fixup_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(bin_ != nullptr);
    bin_->Clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReorderInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .ShuffleInfo.ReorderInfo.BinaryInfo bin = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_bin(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .ShuffleInfo.ReorderInfo.LayoutInfo layout = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_layout(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .ShuffleInfo.ReorderInfo.FixupInfo fixup = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_fixup(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ReorderInfo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ShuffleInfo.ReorderInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .ShuffleInfo.ReorderInfo.BinaryInfo bin = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::bin(this), target, stream);
  }

  // repeated .ShuffleInfo.ReorderInfo.LayoutInfo layout = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_layout_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_layout(i), target, stream);
  }

  // repeated .ShuffleInfo.ReorderInfo.FixupInfo fixup = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_fixup_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, this->_internal_fixup(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ShuffleInfo.ReorderInfo)
  return target;
}

size_t ReorderInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ShuffleInfo.ReorderInfo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .ShuffleInfo.ReorderInfo.LayoutInfo layout = 2;
  total_size += 1UL * this->_internal_layout_size();
  for (const auto& msg : this->layout_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .ShuffleInfo.ReorderInfo.FixupInfo fixup = 3;
  total_size += 1UL * this->_internal_fixup_size();
  for (const auto& msg : this->fixup_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // optional .ShuffleInfo.ReorderInfo.BinaryInfo bin = 1;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *bin_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReorderInfo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ShuffleInfo.ReorderInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const ReorderInfo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ReorderInfo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ShuffleInfo.ReorderInfo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ShuffleInfo.ReorderInfo)
    MergeFrom(*source);
  }
}

void ReorderInfo::MergeFrom(const ReorderInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ShuffleInfo.ReorderInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  layout_.MergeFrom(from.layout_);
  fixup_.MergeFrom(from.fixup_);
  if (from._internal_has_bin()) {
    _internal_mutable_bin()->::ShuffleInfo::ReorderInfo_BinaryInfo::MergeFrom(from._internal_bin());
  }
}

void ReorderInfo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ShuffleInfo.ReorderInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReorderInfo::CopyFrom(const ReorderInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ShuffleInfo.ReorderInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReorderInfo::IsInitialized() const {
  return true;
}

void ReorderInfo::InternalSwap(ReorderInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  layout_.InternalSwap(&other->layout_);
  fixup_.InternalSwap(&other->fixup_);
  swap(bin_, other->bin_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ReorderInfo::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_shuffleInfo_2eproto_getter, &descriptor_table_shuffleInfo_2eproto_once,
      file_level_metadata_shuffleInfo_2eproto[4]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ShuffleInfo
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ShuffleInfo::ReorderInfo_BinaryInfo* Arena::CreateMaybeMessage< ::ShuffleInfo::ReorderInfo_BinaryInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ShuffleInfo::ReorderInfo_BinaryInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::ShuffleInfo::ReorderInfo_LayoutInfo* Arena::CreateMaybeMessage< ::ShuffleInfo::ReorderInfo_LayoutInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ShuffleInfo::ReorderInfo_LayoutInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::ShuffleInfo::ReorderInfo_FixupInfo_FixupTuple* Arena::CreateMaybeMessage< ::ShuffleInfo::ReorderInfo_FixupInfo_FixupTuple >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ShuffleInfo::ReorderInfo_FixupInfo_FixupTuple >(arena);
}
template<> PROTOBUF_NOINLINE ::ShuffleInfo::ReorderInfo_FixupInfo* Arena::CreateMaybeMessage< ::ShuffleInfo::ReorderInfo_FixupInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ShuffleInfo::ReorderInfo_FixupInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::ShuffleInfo::ReorderInfo* Arena::CreateMaybeMessage< ::ShuffleInfo::ReorderInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ShuffleInfo::ReorderInfo >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
